build:
  version: "0.9"

accounts:
  message: "Welcome to Simple Bank accounts related QA APIs"
  contactDetails:
    name: "John Doe - QA Leader"
    email: "{cipher}8348f76c285f70d25d66675332d0afcce2b20a5982ec1c54e5f7ca32791522d552a38ddd228676a3ceb0c0f329cf7140"
